name: Question
description: Ask a question
title: "Question title"
labels: [question]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe your question
      description: A clear and concise description of your question.
      placeholder: Can I ask that [...]